### ISSUE TITLE
4.6.0 install script worked great 

### ISSUE THREAD

**Issue by ncouture** [Qengineering/Install-OpenCV-Raspberry-Pi-64-bits#2]
I've been wanting to build opencv on my RPI for a long time now and never got around to it.

This made the initial process a breeze and I could spend time looking into how I'm going to overclock my device instead of compiling software.

Thank you! :-)

**Comment by Qengineering** [comment]
You're welcome! [Tip](https://qengineering.eu/overclocking-the-raspberry-pi-4.html)
